### ISSUE TITLE
Is it possible to use cygpaths when running the task from a cgwin terminal?

### ISSUE THREAD

**Issue by mrt181** [Scuilion/gradle-syntastic-plugin#10]
I am using cygwin/vim on my windows machine. The plugin creates windows paths, which are useless for syntastic in this environment.

On my ubunut machine everything is fine.

Do you have an idea how to recognize through groovy if the plugin runs in a cygwin enviroment?
I haven't found anything yet, would try to do the change myself then.

**Comment by Scuilion** [comment]
So far I haven't been able to find a good solution to this other than hard coding an option. Even Apache Commons library does not have a method, which makes me think there is not good way to determine if the system is Cygwin based. 

On windows, I just used GVim.

**Comment by Scuilion** [comment]
Give [this](https://github.com/Scuilion/gradle-syntastic-plugin/tree/cygpath) branch a try. You'll have to publish it locally:
```./gradle pTML```

and update your build file:
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
    dependencies {
        classpath 'com.scuilion.syntastic:gradle-syntastic-plugin:0.3.6'
    }
}

apply plugin: 'java'
apply plugin: 'com.scuilion.syntastic' 
```
