### ISSUE TITLE
gradle nested project

### ISSUE THREAD

**Issue by alnavegante** [Scuilion/gradle-syntastic-plugin#11]
The context: the plugin successfully creates the ".synstastic_javac_config" file in the root folder of the project, and also adds some paths relative to the /root/build  folder. However there are no extra paths for the sub-folders (aka. sub-projects).  

The problem:  when going to one of the sub-projects and trying to debug (any) class, syntastic does not recognize any "import" from my own classes (located in parallel folders). 

I was thinking about writing a simple script that iterates over all sub-folders, extract the paths to all *.jar and *.class and put them in the ".synstastic_javac_config" file ... just for checking if this is really the problem. Tho. I prefer to write this first :)

**Comment by Scuilion** [comment]
This has been fixed in v0.3.8. 

Let me know if you have any problems.

**Comment by alnavegante** [comment]
Yes, now it works flawlessly. Thanks!
