### ISSUE TITLE
Add support for older jdks

### ISSUE THREAD

**Issue by calid** [Scuilion/gradle-syntastic-plugin#9]
When installing the plugin I get the following error:

```
java.lang.UnsupportedClassVersionError: com/scuilion/gradle/plugins/syntastic/SyntasticPlugin : Unsupported major.minor version 52.0
> com/scuilion/gradle/plugins/syntastic/SyntasticPlugin : Unsupported major.minor version 52.0
```

I know java 7 is technically end-of-life, but a lot of people are still using it (especially for work), can you  upload release artifacts with an older target compatibility?

**Comment by Scuilion** [comment]
Try this: https://plugins.gradle.org/plugin/com.scuilion.syntastic/0.3.6-java7

**Comment by calid** [comment]
Great success!  thank you
